import {record} from './storage.js';import {toast,formatTime,modal} from './ui.js';
const fleet=[4,3,3,2,2,2,1,1,1,1];
export function mountBattleship(root,state,level='medium'){
 let you=placeFleet(),bot=placeFleet(),turn='you',seconds=0,over=false,botQueue=[];root.innerHTML=layout();const boards=[...root.querySelectorAll('.board')],timer=root.querySelector('.timer'),status=root.querySelector('[data-status]');render();const tick=setInterval(()=>{if(!over){seconds++;timer.textContent=formatTime(seconds)}},1000);root._cleanup=()=>clearInterval(tick);root.querySelector('[data-restart]').onclick=()=>{you=placeFleet();bot=placeFleet();turn='you';seconds=0;over=false;botQueue=[];render()};root.querySelector('[data-resign]').onclick=()=>modal({title:'Покинуть бой?',text:'Поражение будет записано в статистику.',danger:true,confirm:'Покинуть',onConfirm:()=>finish('Поражение')});
 function layout(){return `<div class="sea-wrap"><div><h3 class="panel-title">Ваш флот</h3><div class="board sea-board" data-sea="you"></div></div><div><h3 class="panel-title">Воды противника</h3><div class="board sea-board" data-sea="bot"></div></div></div><div class="game-info" style="margin-top:18px;grid-template-columns:1fr 1fr"><div class="game-panel"><div class="player-row active" data-you><div class="face">${state.profile.avatar}</div><span><b>${state.profile.nickname}</b><small>Командующий</small></span></div><div class="timer">00:00</div><div class="player-row" data-bot><div class="face">⚓</div><span><b>ADMIRAL / ${level.toUpperCase()}</b><small>Противник</small></span></div></div><div class="game-panel"><h3 class="panel-title" data-status>Выберите цель</h3><p class="muted">Корабли расставлены автоматически. Попадание даёт дополнительный выстрел.</p><button class="btn btn-secondary btn-wide" data-restart>Новая расстановка</button><button class="btn btn-ghost btn-wide" style="margin-top:8px" data-resign>Сдаться</button></div></div>`}
 function placeFleet(){let cells=Array.from({length:10},()=>Array.from({length:10},()=>({ship:false,shot:false})));for(const len of fleet){let ok=false;while(!ok){const v=Math.random()<.5,r=Math.floor(Math.random()*(v?11-len:10)),c=Math.floor(Math.random()*(v?10:11-len));ok=true;for(let i=0;i<len;i++){let rr=r+(v?i:0),cc=c+(v?0:i);for(let y=rr-1;y<=rr+1;y++)for(let x=cc-1;x<=cc+1;x++)if(cells[y]?.[x]?.ship)ok=false}if(ok)for(let i=0;i<len;i++)cells[r+(v?i:0)][c+(v?0:i)].ship=true}}return cells}
 function render(){boards.forEach((board,idx)=>{const data=idx?bot:you;board.innerHTML='';for(let r=0;r<10;r++)for(let c=0;c<10;c++){const x=data[r][c],cell=document.createElement('button');cell.className='sea-cell';if(!idx&&x.ship)cell.classList.add('ship');if(x.shot)cell.classList.add(x.ship?'hit':'miss');if(idx)cell.onclick=()=>shoot(r,c);cell.title=`${String.fromCharCode(65+c)}${r+1}`;board.append(cell)}});status.textContent=over?'Бой завершён':turn==='you'?'Ваш залп':'Противник целится…';root.querySelector('[data-you]').classList.toggle('active',turn==='you');root.querySelector('[data-bot]').classList.toggle('active',turn==='bot')}
 function shoot(r,c){if(over||turn!=='you'||bot[r][c].shot)return;bot[r][c].shot=true;if(bot[r][c].ship){toast('Попадание!',`${String.fromCharCode(65+c)}${r+1}`);if(allSunk(bot))return finish('Победа')}else{turn='bot';setTimeout(botShoot,500)}render()}
 function botShoot(){if(over)return;let r,c;do{if(level!=='easy'&&botQueue.length)[r,c]=botQueue.shift();else{r=Math.floor(Math.random()*10);c=Math.floor(Math.random()*10);if(level==='expert'&&(r+c)%2)continue}}while(!you[r]?.[c]||you[r][c].shot);you[r][c].shot=true;if(you[r][c].ship){for(const[d,e]of[[1,0],[-1,0],[0,1],[0,-1]])if(you[r+d]?.[c+e]&&!you[r+d][c+e].shot)botQueue.push([r+d,c+e]);if(allSunk(you))return finish('Поражение');setTimeout(botShoot,450)}else turn='you';render()}
 function allSunk(data){return !data.flat().some(x=>x.ship&&!x.shot)}function finish(result){if(over)return;over=true;record(state,'battleship',result);render();toast(result,result==='Победа'?'Вражеский флот уничтожен. +100 очков':'Ваш флот потерян.')}
}
