import {record} from './storage.js';import {toast,formatTime,modal} from './ui.js';
export function mountCheckers(root,state,level='medium'){
 let b=initial(),turn='r',selected=null,legal=[],moves=0,seconds=0,over=false;root.innerHTML=layout();const board=root.querySelector('.board'),timer=root.querySelector('.timer'),status=root.querySelector('[data-status]');render();const tick=setInterval(()=>{if(!over){seconds++;timer.textContent=formatTime(seconds)}},1000);root._cleanup=()=>clearInterval(tick);root.querySelector('[data-restart]').onclick=()=>{b=initial();turn='r';selected=null;over=false;seconds=0;render()};root.querySelector('[data-resign]').onclick=()=>modal({title:'Сдаться?',text:'Результат сохранится в статистике.',danger:true,confirm:'Сдаться',onConfirm:()=>finish('Поражение')});
 function layout(){return `<div class="game-layout"><div class="game-panel"><div class="board checkers-board"></div></div><div class="game-info"><div class="game-panel"><div class="player-row" data-bot><div class="face">🧠</div><span><b>BOT / ${level.toUpperCase()}</b><small>Светлые</small></span></div><div class="timer">00:00</div><div class="player-row active" data-you><div class="face">${state.profile.avatar}</div><span><b>${state.profile.nickname}</b><small>Красные</small></span></div></div><div class="game-panel"><h3 class="panel-title" data-status>Ваш ход</h3><p class="muted">Взятие выполняется прыжком через шашку. Дойдите до последней линии, чтобы получить дамку.</p><button class="btn btn-secondary btn-wide" data-restart>Новая партия</button><button class="btn btn-ghost btn-wide" style="margin-top:8px" data-resign>Сдаться</button></div></div>`}
 function initial(){let x=Array.from({length:8},()=>Array(8).fill(null));for(let r=0;r<3;r++)for(let c=0;c<8;c++)if((r+c)%2)x[r][c]={c:'c',k:false};for(let r=5;r<8;r++)for(let c=0;c<8;c++)if((r+c)%2)x[r][c]={c:'r',k:false};return x}
 function render(){board.innerHTML='';for(let r=0;r<8;r++)for(let c=0;c<8;c++){const s=document.createElement('button');s.className=`square ${(r+c)%2?'dark':'light'}`;if(selected&&selected[0]===r&&selected[1]===c)s.classList.add('selected');if(legal.some(x=>x[0]===r&&x[1]===c))s.classList.add(b[r][c]?'capture':'legal');if(b[r][c])s.innerHTML=`<i class="checker ${b[r][c].c==='r'?'red':'cream'} ${b[r][c].k?'king':''}"></i>`;s.onclick=()=>click(r,c);board.append(s)}status.textContent=over?'Партия завершена':turn==='r'?'Ваш ход':'Бот думает…';root.querySelector('[data-you]').classList.toggle('active',turn==='r');root.querySelector('[data-bot]').classList.toggle('active',turn==='c')}
 function options(r,c){const p=b[r][c],out=[];if(!p)return out;const dirs=p.k?[-1,1]:[p.c==='r'?-1:1];for(const dr of dirs)for(const dc of[-1,1]){let rr=r+dr,cc=c+dc;if(!b[rr]?.[cc]){if(rr>=0&&cc>=0&&cc<8)out.push([rr,cc])}else if(b[rr][cc].c!==p.c&&!b[r+2*dr]?.[c+2*dc]&&r+2*dr>=0&&r+2*dr<8&&c+2*dc>=0&&c+2*dc<8)out.push([r+2*dr,c+2*dc])}return out}
 function click(r,c){if(over||turn!=='r')return;if(selected&&legal.some(x=>x[0]===r&&x[1]===c)){apply(selected,[r,c]);selected=null;legal=[];render();if(!over)setTimeout(bot,380)}else if(b[r][c]?.c==='r'){selected=[r,c];legal=options(r,c);render()}}
 function apply(a,z){let p=b[a[0]][a[1]];b[z[0]][z[1]]=p;b[a[0]][a[1]]=null;if(Math.abs(z[0]-a[0])===2)b[(z[0]+a[0])/2][(z[1]+a[1])/2]=null;if((p.c==='r'&&z[0]===0)||(p.c==='c'&&z[0]===7))p.k=true;moves++;turn=p.c==='r'?'c':'r';checkEnd()}
 function bot(){let all=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(b[r][c]?.c==='c')for(const z of options(r,c)){const capture=Math.abs(z[0]-r)===2?5:0,promotion=z[0]===7?3:0;all.push({a:[r,c],z,score:level==='easy'?Math.random():capture+promotion+(level==='expert'?(3.5-Math.abs(3.5-z[1]))*.3:0)+Math.random()})}if(!all.length)return finish('Победа');all.sort((a,z)=>z.score-a.score);apply(all[0].a,all[0].z);render()}
 function checkEnd(){let red=b.flat().some(x=>x?.c==='r'),cream=b.flat().some(x=>x?.c==='c');if(!red)finish('Поражение');if(!cream)finish('Победа')}
 function finish(result){if(over)return;over=true;record(state,'checkers',result);render();toast(result,result==='Победа'?'+100 очков за стратегию':'Реванш уже ждёт.')}
}
