import {firebaseReady} from './firebase-config.js';
import {createRoom,joinRoom,watchRoom,commitGameState,updateRoomAction,leaveRoom,markDisconnected} from './rooms.js?v=6';
import {toast,modal} from './ui.js?v=6';
import {createChessState,chessLegalMoves,applyChessMove,createCheckersState,checkersLegalMoves,applyCheckersMove} from './rules.js?v=6';

const chessGlyph={wk:'♔',wq:'♕',wr:'♖',wb:'♗',wn:'♘',wp:'♙',bk:'♚',bq:'♛',br:'♜',bb:'♝',bn:'♞',bp:'♟'};
const names={chess:'Шахматы',checkers:'Шашки'};

export function initialOnlineState(game){return game==='chess'?createChessState():createCheckersState()}

export function mountOnline(root,game,appState){
  let identity=null,unsubscribe=null,room=null,selected=null,disconnectTimer=null,busy=false;
  root._cleanup=()=>{unsubscribe?.();clearTimeout(disconnectTimer);if(identity)leaveRoom(identity.code,identity).catch(()=>{});identity=null};
  if(!firebaseReady){root.innerHTML=`<div class="online-notice" role="status"><span class="online-notice__icon">⌁</span><div><h2>Firebase не подключён</h2><p>Онлайн-режим требует подключения Firebase. Локальные игры, профиль и задания продолжают работать.</p></div></div>`;return}
  showLobby();

  function showLobby(){
    root.innerHTML=`<div class="online-grid"><section class="room-card room-card--create"><span class="eyebrow">Новая сессия</span><div class="room-card__mark">＋</div><h2>Создать комнату</h2><p>Получите уникальный код и отправьте его второму игроку.</p><button class="btn btn-primary btn-wide" data-create>Создать комнату</button></section><section class="room-card"><span class="eyebrow">Есть приглашение</span><div class="room-card__mark">⌁</div><h2>Войти по коду</h2><label class="room-label" for="room-code">Код комнаты</label><input id="room-code" class="field room-code-input" inputmode="numeric" autocomplete="off" placeholder="DAV-0000" maxlength="8"><button class="btn btn-secondary btn-wide" data-join>Присоединиться</button></section></div><p class="online-security">Соединение защищается Firebase Authentication и правилами Realtime Database.</p>`;
    root.querySelector('[data-create]').onclick=async e=>{setBusy(e.currentTarget,true,'Создаём…');try{identity=await createRoom(game,appState.profile,initialOnlineState(game));await enterRoom()}catch(err){showError(err)}finally{if(e.currentTarget?.isConnected)setBusy(e.currentTarget,false,'Создать комнату')}};
    root.querySelector('[data-join]').onclick=async e=>{setBusy(e.currentTarget,true,'Подключаем…');try{identity=await joinRoom(root.querySelector('#room-code').value,game,appState.profile);await enterRoom();toast('Подключение установлено','Вы в комнате '+identity.code)}catch(err){showError(err)}finally{if(e.currentTarget?.isConnected)setBusy(e.currentTarget,false,'Присоединиться')}};
  }
  async function enterRoom(){root.innerHTML=`<div class="room-shell"><div class="room-loading"><i></i><b>Подключаем realtime-сессию</b><small>${identity.code}</small></div></div>`;unsubscribe=await watchRoom(identity.code,next=>{if(!next){toast('Комната закрыта');identity=null;showLobby();return}room=next;selected=game==='checkers'&&room.turn===identity.role?room.gameState?.forced||null:null;renderRoom();watchPresence()},showError)}
  function renderRoom(){
    const opponent=other(identity.role),myTurn=room.turn===identity.role&&room.status==='playing',waiting=room.status==='waiting',opponentPresent=room[opponent]&&room.presence?.[room[opponent].id];document.title=`${names[game]} онлайн — DavGame`;
    root.innerHTML=`<section class="room-bar"><div><span class="eyebrow">Комната</span><button class="room-code" data-copy aria-label="Скопировать код комнаты">${identity.code} <span>⧉</span></button></div><div class="connection ${opponentPresent?'is-online':''}"><i></i>${waiting?'Ожидание игрока':opponentPresent?'Оба игрока в сети':'Нет соединения с соперником'}</div><button class="btn btn-ghost" data-leave>Выйти</button></section><section class="versus"><div class="online-player ${room.turn==='host'?'is-turn':''}"><span>${room.host.avatar}</span><div><b>${escapeHtml(room.host.name)}</b><small>HOST · ${sideName(game,'host')}</small></div></div><div class="versus__center"><b>VS</b><small>${statusText(room)}</small></div><div class="online-player online-player--right ${room.turn==='guest'?'is-turn':''}"><div><b>${room.guest?escapeHtml(room.guest.name):'Ожидаем игрока'}</b><small>GUEST · ${sideName(game,'guest')}</small></div><span>${room.guest?.avatar||'◌'}</span></div></section><div class="online-stage" data-stage></div><section class="match-actions"><span>${myTurn?'Ваш ход':waiting?'Отправьте код другу':'Ход соперника'}</span><div><button class="btn btn-ghost" data-draw ${room.status!=='playing'?'disabled':''}>Предложить ничью</button><button class="btn btn-danger" data-resign ${room.status!=='playing'?'disabled':''}>Сдаться</button></div></section>`;
    root.querySelector('[data-copy]').onclick=async()=>{await navigator.clipboard?.writeText(identity.code);toast('Код скопирован',identity.code)};root.querySelector('[data-leave]').onclick=confirmLeave;root.querySelector('[data-resign]').onclick=confirmResign;root.querySelector('[data-draw]').onclick=()=>updateRoomAction(identity.code,identity,'draw').catch(showError);renderGame(root.querySelector('[data-stage]'),myTurn);if(room.drawOffer&&room.drawOffer!==identity.role)showDrawOffer();
  }
  function renderGame(stage,myTurn){if(room.status==='waiting'){stage.innerHTML=`<div class="waiting-state"><div class="waiting-rings"><i></i><i></i><i></i></div><h2>Ожидание второго игрока</h2><p>Экран обновится автоматически после подключения друга.</p></div>`;return}if(['finished','abandoned','closed'].includes(room.status)){renderResult(stage);return}if(game==='chess')renderChess(stage,myTurn);else renderCheckers(stage,myTurn)}
  function renderChess(stage,myTurn){
    const state=room.gameState,board=state.board,own=identity.role==='host'?'w':'b',moves=selected?chessLegalMoves(state,selected[0],selected[1]):[],checkKing=state.check?findKing(board,state.turn):null;
    stage.innerHTML=`<div class="online-board-wrap"><div class="board chess-board online-board ${identity.role==='guest'?'flipped':''}"></div><aside class="online-aside"><span class="eyebrow">Последний ход</span><strong>${formatMove(state.lastMove)||'—'}</strong><p>${state.check?'Король под шахом.':'Позиция синхронизирована.'}</p><small>Ревизия ${state.revision}</small></aside></div>`;
    const el=stage.querySelector('.board');for(let r=0;r<8;r++)for(let c=0;c<8;c++){const square=document.createElement('button'),piece=board[r][c];square.type='button';square.className=`square ${(r+c)%2?'dark':'light'}`;if(same(selected,[r,c]))square.classList.add('selected');if(moves.some(x=>same(x,[r,c])))square.classList.add(piece?'capture':'legal');if(state.lastMove&&(same(state.lastMove.from,[r,c])||same(state.lastMove.to,[r,c])))square.classList.add('last-move');if(same(checkKing,[r,c]))square.classList.add('in-check');if(piece)square.innerHTML=`<span class="chess-piece ${piece[0]==='w'?'piece-white':'piece-black'}">${chessGlyph[piece]}</span>`;square.disabled=!myTurn;square.onclick=()=>{if(selected&&moves.some(x=>same(x,[r,c])))submitChess(selected,[r,c]);else if(piece?.[0]===own){selected=[r,c];renderRoom()}};el.append(square)}
  }
  async function submitChess(from,to){if(busy)return;const old=room.gameState;if((identity.role==='host'?'w':'b')!==old.turn)return;const next=applyChessMove(old,from,to);if(!next)return;const result=next.result?{winner:next.result.winner==='w'?'host':next.result.winner==='b'?'guest':null,reason:next.result.reason}:null;busy=true;selected=null;try{await commitGameState(identity.code,identity,old.revision,next,other(identity.role),result)}catch(err){showError(err)}finally{busy=false}}
  function renderCheckers(stage,myTurn){
    const state=room.gameState,board=state.board,own=identity.role==='host'?'r':'c',moves=selected?checkersLegalMoves(state,selected[0],selected[1]):[];
    stage.innerHTML=`<div class="online-board-wrap"><div class="board checkers-board online-board ${identity.role==='guest'?'flipped':''}"></div><aside class="online-aside"><span class="eyebrow">Правило хода</span><strong>${state.forced?'Продолжите взятие':'Взятие обязательно'}</strong><p>Позиция и очередь подтверждаются транзакцией Firebase.</p><small>Ревизия ${state.revision}</small></aside></div>`;
    const el=stage.querySelector('.board');for(let r=0;r<8;r++)for(let c=0;c<8;c++){const square=document.createElement('button'),piece=board[r][c];square.type='button';square.className=`square ${(r+c)%2?'dark':'light'}`;if(same(selected,[r,c]))square.classList.add('selected');if(moves.some(x=>same(x,[r,c])))square.classList.add('legal');if(state.lastMove&&(same(state.lastMove.from,[r,c])||same(state.lastMove.to,[r,c])))square.classList.add('last-move');if(piece)square.innerHTML=`<span class="checker ${piece.toLowerCase()==='r'?'red':'cream'} ${piece===piece.toUpperCase()?'king':''}"></span>`;square.disabled=!myTurn;square.onclick=()=>{if(selected&&moves.some(x=>same(x,[r,c])))submitChecker(selected,[r,c]);else if(piece?.toLowerCase()===own){selected=[r,c];renderRoom()}};el.append(square)}
  }
  async function submitChecker(from,to){if(busy)return;const old=room.gameState;if((identity.role==='host'?'r':'c')!==old.turn)return;const next=applyCheckersMove(old,from,to);if(!next)return;const result=next.result?{winner:next.result.winner==='r'?'host':'guest',reason:next.result.reason}:null,nextRole=next.forced?identity.role:other(identity.role);busy=true;selected=next.forced;try{await commitGameState(identity.code,identity,old.revision,next,nextRole,result)}catch(err){showError(err)}finally{busy=false}}
  function renderResult(stage){const won=room.result?.winner===identity.role,draw=!room.result?.winner;stage.innerHTML=`<div class="match-result"><span>${draw?'◇':won?'◆':'○'}</span><h2>${draw?'Ничья':won?'Победа':'Поражение'}</h2><p>${resultReason(room.result?.reason)}</p><button class="btn btn-primary" data-rematch>Предложить реванш</button><small>${room.rematch?.[other(identity.role)]?'Соперник уже ждёт реванш':'Для старта нужны оба игрока'}</small></div>`;stage.querySelector('[data-rematch]').onclick=()=>updateRoomAction(identity.code,identity,'rematch',{gameState:initialOnlineState(game)}).catch(showError)}
  function showDrawOffer(){if(document.querySelector('[data-draw-modal]'))return;modal({title:'Соперник предлагает ничью',text:'Завершить партию без победителя?',confirm:'Принять ничью',onConfirm:()=>updateRoomAction(identity.code,identity,'draw-accept').catch(showError),onCancel:()=>updateRoomAction(identity.code,identity,'draw-decline').catch(showError),extra:'<div data-draw-modal></div>'})}
  function confirmResign(){modal({title:'Сдаться?',text:'Соперник будет объявлен победителем.',danger:true,confirm:'Сдаться',onConfirm:()=>updateRoomAction(identity.code,identity,'resign').catch(showError)})}
  function confirmLeave(){modal({title:'Выйти из комнаты?',text:'Матч будет завершён, а соперник увидит ваш выход.',danger:true,confirm:'Выйти',onConfirm:async()=>{await leaveRoom(identity.code,identity).catch(()=>{});unsubscribe?.();identity=null;room=null;showLobby()}})}
  function watchPresence(){clearTimeout(disconnectTimer);if(room.status!=='playing')return;const missing=other(identity.role),player=room[missing];if(player&&!room.presence?.[player.id])disconnectTimer=setTimeout(()=>markDisconnected(identity.code,identity,missing).catch(()=>{}),6000)}
  function showError(err){const raw=err?.message||'',permission=/permission.?denied/i.test(raw)||err?.code==='PERMISSION_DENIED'||err?.code==='permission-denied';toast('Не удалось выполнить действие',permission?'Firebase отклонил запрос. Опубликуйте актуальные правила базы.':raw||'Проверьте соединение и настройки Firebase.')}
  function setBusy(button,value,label){busy=value;button.disabled=value;button.textContent=label}
}

function other(role){return role==='host'?'guest':'host'}function sideName(game,role){return game==='chess'?(role==='host'?'белые':'чёрные'):(role==='host'?'красные':'светлые')}function statusText(room){return room.status==='waiting'?'WAITING':room.status==='playing'?'LIVE':room.status==='abandoned'?'DISCONNECT':'FINISHED'}function formatMove(move){return move?`${String.fromCharCode(65+move.from[1])}${8-move.from[0]} → ${String.fromCharCode(65+move.to[1])}${8-move.to[0]}`:''}function resultReason(reason){return({checkmate:'Мат. Королю некуда отступать.',stalemate:'Пат: допустимых ходов нет.',capture:'У соперника не осталось хода.',resign:'Соперник завершил партию.',draw:'Предложение ничьей принято.',disconnect:'Соперник покинул комнату.'})[reason]||'Матч завершён.'}function findKing(board,color){for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(board[r][c]===color+'k')return[r,c];return null}function same(a,b){return a?.[0]===b?.[0]&&a?.[1]===b?.[1]}function escapeHtml(value){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
