import {firebaseReady} from './firebase-config.js';
import {createRoom,joinRoom,watchRoom,commitGameState,updateRoomAction,leaveRoom,markDisconnected} from './rooms.js';
import {toast,modal} from './ui.js';

const chessGlyph={wk:'♔',wq:'♕',wr:'♖',wb:'♗',wn:'♘',wp:'♙',bk:'♚',bq:'♛',br:'♜',bb:'♝',bn:'♞',bp:'♟'};
const names={chess:'Шахматы',checkers:'Шашки',battleship:'Морской бой'};

export function initialOnlineState(game){
  if(game==='chess')return {revision:0,board:chessInitial(),lastMove:null,check:false,castling:{wK:true,wQ:true,bK:true,bQ:true}};
  if(game==='checkers')return {revision:0,board:checkersInitial(),lastMove:null,forced:null};
  return {revision:0,boards:{host:seaFleet(),guest:seaFleet()},lastShot:null};
}

export function mountOnline(root,game,appState){
  let identity=null,unsubscribe=null,room=null,selected=null,disconnectTimer=null,busy=false;
  root._cleanup=()=>{unsubscribe?.();clearTimeout(disconnectTimer);if(identity)leaveRoom(identity.code,identity).catch(()=>{});identity=null};
  if(!firebaseReady){root.innerHTML=`<div class="online-notice" role="status"><span class="online-notice__icon">⌁</span><div><h2>Firebase не подключён</h2><p>Онлайн-режим требует подключения Firebase. Локальные игры, профиль и задания продолжают работать.</p><a class="btn btn-ghost" href="./README.md" target="_blank">Инструкция по настройке</a></div></div>`;return}
  showLobby();

  function showLobby(){
    root.innerHTML=`<div class="online-grid"><section class="room-card room-card--create"><span class="eyebrow">Новая сессия</span><div class="room-card__mark">＋</div><h2>Создать комнату</h2><p>Получите уникальный код и отправьте его второму игроку.</p><button class="btn btn-primary btn-wide" data-create>Создать комнату</button></section><section class="room-card"><span class="eyebrow">Есть приглашение</span><div class="room-card__mark">⌁</div><h2>Войти по коду</h2><label class="room-label" for="room-code">Код комнаты</label><input id="room-code" class="field room-code-input" inputmode="numeric" autocomplete="off" placeholder="DAV-0000" maxlength="8"><button class="btn btn-secondary btn-wide" data-join>Присоединиться</button></section></div><p class="online-security">Соединение защищается Firebase Authentication и правилами Realtime Database.</p>`;
    root.querySelector('[data-create]').onclick=async e=>{setBusy(e.currentTarget,true,'Создаём…');try{identity=await createRoom(game,appState.profile,initialOnlineState(game));await enterRoom()}catch(err){showError(err)}finally{setBusy(e.currentTarget,false,'Создать комнату')}};
    root.querySelector('[data-join]').onclick=async e=>{setBusy(e.currentTarget,true,'Подключаем…');try{identity=await joinRoom(root.querySelector('#room-code').value,game,appState.profile);await enterRoom();toast('Подключение установлено','Вы в комнате '+identity.code)}catch(err){showError(err)}finally{if(e.currentTarget?.isConnected)setBusy(e.currentTarget,false,'Присоединиться')}};
  }

  async function enterRoom(){
    root.innerHTML=`<div class="room-shell"><div class="room-loading"><i></i><b>Подключаем realtime-сессию</b><small>${identity.code}</small></div></div>`;
    unsubscribe=await watchRoom(identity.code,next=>{if(!next){toast('Комната закрыта');showLobby();return}room=next;renderRoom();watchPresence()},showError);
  }

  function renderRoom(){
    const opponent=identity.role==='host'?'guest':'host',myTurn=room.turn===identity.role&&room.status==='playing',waiting=room.status==='waiting',opponentPresent=room[opponent]&&room.presence?.[room[opponent].id];
    document.title=`${names[game]} онлайн — DavGame`;
    root.innerHTML=`<section class="room-bar"><div><span class="eyebrow">Комната</span><button class="room-code" data-copy aria-label="Скопировать код комнаты">${identity.code} <span>⧉</span></button></div><div class="connection ${opponentPresent?'is-online':''}"><i></i>${waiting?'Ожидание игрока':opponentPresent?'Оба игрока в сети':'Нет соединения с соперником'}</div><button class="btn btn-ghost" data-leave>Выйти</button></section><section class="versus"><div class="online-player ${room.turn==='host'?'is-turn':''}"><span>${room.host.avatar}</span><div><b>${escapeHtml(room.host.name)}</b><small>HOST · ${sideName(game,'host')}</small></div></div><div class="versus__center"><b>VS</b><small>${statusText(room)}</small></div><div class="online-player online-player--right ${room.turn==='guest'?'is-turn':''}"><div><b>${room.guest?escapeHtml(room.guest.name):'Ожидаем игрока'}</b><small>GUEST · ${sideName(game,'guest')}</small></div><span>${room.guest?.avatar||'◌'}</span></div></section><div class="online-stage" data-stage></div><section class="match-actions"><span>${myTurn?'Ваш ход':waiting?'Отправьте код другу':'Ход соперника'}</span><div><button class="btn btn-ghost" data-draw ${room.status!=='playing'?'disabled':''}>Предложить ничью</button><button class="btn btn-danger" data-resign ${room.status!=='playing'?'disabled':''}>Сдаться</button></div></section>${battleshipWarning()}`;
    root.querySelector('[data-copy]').onclick=async()=>{await navigator.clipboard?.writeText(identity.code);toast('Код скопирован',identity.code)};
    root.querySelector('[data-leave]').onclick=()=>confirmLeave();root.querySelector('[data-resign]').onclick=()=>confirmResign();root.querySelector('[data-draw]').onclick=()=>updateRoomAction(identity.code,identity,'draw').catch(showError);
    renderGame(root.querySelector('[data-stage]'),myTurn);
    if(room.drawOffer&&room.drawOffer!==identity.role)showDrawOffer();
  }

  function renderGame(stage,myTurn){
    if(room.status==='waiting'){stage.innerHTML=`<div class="waiting-state"><div class="waiting-rings"><i></i><i></i><i></i></div><h2>Ожидание второго игрока</h2><p>Код уже существует в Firebase. Экран обновится автоматически после подключения друга.</p></div>`;return}
    if(['finished','abandoned','closed'].includes(room.status)){renderResult(stage);return}
    if(game==='chess')renderChess(stage,myTurn);if(game==='checkers')renderCheckers(stage,myTurn);if(game==='battleship')renderSea(stage,myTurn)
  }

  function renderChess(stage,myTurn){
    const board=room.gameState.board,own=identity.role==='host'?'w':'b';stage.innerHTML=`<div class="online-board-wrap"><div class="board chess-board online-board ${identity.role==='guest'?'flipped':''}"></div><aside class="online-aside"><span class="eyebrow">Последний ход</span><strong>${formatMove(room.gameState.lastMove)||'—'}</strong><p>${room.gameState.check?'Король под шахом. Защитите позицию.':'Позиция синхронизирована.'}</p><small>Ревизия ${room.gameState.revision}</small></aside></div>`;
    const el=stage.querySelector('.board');for(let r=0;r<8;r++)for(let c=0;c<8;c++){const s=document.createElement('button'),p=board[r][c],moves=selected?chessLegal(board,selected[0],selected[1],room.gameState.castling):[];s.className=`square ${(r+c)%2?'dark':'light'}`;if(selected?.[0]===r&&selected?.[1]===c)s.classList.add('selected');if(moves.some(x=>x[0]===r&&x[1]===c))s.classList.add(p?'capture':'legal');s.textContent=p?chessGlyph[p]:'';s.disabled=!myTurn;s.onclick=()=>{if(selected&&moves.some(x=>x[0]===r&&x[1]===c))submitChess(selected,[r,c]);else if(p?.[0]===own){selected=[r,c];renderRoom()}};el.append(s)}
  }

  async function submitChess(from,to){if(busy)return;const old=room.gameState,b=old.board.map(row=>[...row]),piece=b[from[0]][from[1]],rights={...(old.castling||{})};if(!piece||piece[0]!== (identity.role==='host'?'w':'b'))return;const legal=chessLegal(b,from[0],from[1],rights);if(!legal.some(x=>x[0]===to[0]&&x[1]===to[1]))return;const captured=b[to[0]][to[1]];b[to[0]][to[1]]=piece;b[from[0]][from[1]]=null;if(piece[1]==='k'&&Math.abs(to[1]-from[1])===2){const rookFrom=to[1]===6?7:0,rookTo=to[1]===6?5:3;b[to[0]][rookTo]=b[to[0]][rookFrom];b[to[0]][rookFrom]=null}if(piece[1]==='p'&&(to[0]===0||to[0]===7))b[to[0]][to[1]]=piece[0]+'q';updateCastlingRights(rights,piece,from,captured,to);const nextRole=other(identity.role),nextColor=piece[0]==='w'?'b':'w',check=isKingAttacked(b,nextColor),hasMove=hasChessMove(b,nextColor,rights);let result=null;if(captured?.[1]==='k'||(!hasMove&&check))result={winner:identity.role,reason:'checkmate'};else if(!hasMove)result={winner:null,reason:'stalemate'};const next={...old,revision:old.revision+1,board:b,lastMove:{from,to,piece},check,castling:rights};selected=null;busy=true;try{await commitGameState(identity.code,identity,old.revision,next,nextRole,result)}catch(err){showError(err)}finally{busy=false}}

  function renderCheckers(stage,myTurn){
    const b=room.gameState.board,own=identity.role==='host'?'r':'c',moves=selected?checkerMoves(b,selected[0],selected[1],own,room.gameState.forced):[];stage.innerHTML=`<div class="online-board-wrap"><div class="board checkers-board online-board ${identity.role==='guest'?'flipped':''}"></div><aside class="online-aside"><span class="eyebrow">Правило хода</span><strong>${room.gameState.forced?'Продолжите взятие':'Взятие обязательно'}</strong><p>Ход подтверждается транзакцией Firebase.</p><small>Ревизия ${room.gameState.revision}</small></aside></div>`;const el=stage.querySelector('.board');for(let r=0;r<8;r++)for(let c=0;c<8;c++){const s=document.createElement('button'),p=b[r][c];s.className=`square ${(r+c)%2?'dark':'light'}`;if(selected?.[0]===r&&selected?.[1]===c)s.classList.add('selected');if(moves.some(x=>x[0]===r&&x[1]===c))s.classList.add('legal');if(p)s.innerHTML=`<i class="checker ${p.toLowerCase()==='r'?'red':'cream'} ${p===p.toUpperCase()?'king':''}"></i>`;s.disabled=!myTurn;s.onclick=()=>{if(selected&&moves.some(x=>x[0]===r&&x[1]===c))submitChecker(selected,[r,c]);else if(p?.toLowerCase()===own){selected=[r,c];renderRoom()}};el.append(s)}
  }

  async function submitChecker(from,to){if(busy)return;const old=room.gameState,b=old.board.map(row=>[...row]),piece=b[from[0]][from[1]],own=identity.role==='host'?'r':'c',legal=checkerMoves(b,from[0],from[1],own,old.forced);if(!piece||piece.toLowerCase()!==own||!legal.some(x=>x[0]===to[0]&&x[1]===to[1]))return;b[to[0]][to[1]]=piece;b[from[0]][from[1]]=null;const capture=Math.abs(to[0]-from[0])===2;if(capture)b[(to[0]+from[0])/2][(to[1]+from[1])/2]=null;if((own==='r'&&to[0]===0)||(own==='c'&&to[0]===7))b[to[0]][to[1]]=piece.toUpperCase();const more=capture&&checkerCaptures(b,to[0],to[1],own).length>0,opponent=own==='r'?'c':'r',hasOpponent=b.flat().some(x=>x?.toLowerCase()===opponent)&&hasCheckerMove(b,opponent);const result=hasOpponent?null:{winner:identity.role,reason:'capture'},next={revision:old.revision+1,board:b,lastMove:{from,to},forced:more?to:null};selected=more?to:null;busy=true;try{await commitGameState(identity.code,identity,old.revision,next,more?identity.role:other(identity.role),result)}catch(err){showError(err)}finally{busy=false}}

  function renderSea(stage,myTurn){
    const mine=room.gameState.boards[identity.role],enemy=room.gameState.boards[other(identity.role)];stage.innerHTML=`<div class="sea-online"><div><h3>Ваш флот</h3><div class="board sea-board" data-mine></div></div><div><h3>Радар противника</h3><div class="board sea-board" data-enemy></div></div></div>`;paintSea(stage.querySelector('[data-mine]'),mine,true,false);paintSea(stage.querySelector('[data-enemy]'),enemy,false,myTurn)
  }
  function paintSea(el,data,reveal,interactive){for(let r=0;r<10;r++)for(let c=0;c<10;c++){const s=document.createElement('button'),v=data[r][c];s.className='sea-cell';if(reveal&&v===1)s.classList.add('ship');if(v===2)s.classList.add('miss');if(v===3)s.classList.add('hit');s.disabled=!interactive||v>=2;s.onclick=()=>submitShot(r,c);el.append(s)}}
  async function submitShot(r,c){if(busy)return;const old=room.gameState,boards={host:old.boards.host.map(x=>[...x]),guest:old.boards.guest.map(x=>[...x])},enemy=boards[other(identity.role)],v=enemy[r][c];if(v>=2)return;const hit=v===1;enemy[r][c]=hit?3:2;const sunk=!enemy.flat().some(x=>x===1),result=sunk?{winner:identity.role,reason:'fleet'}:null,next={revision:old.revision+1,boards,lastShot:{by:identity.role,r,c,hit}};busy=true;try{await commitGameState(identity.code,identity,old.revision,next,hit?identity.role:other(identity.role),result);toast(hit?'Попадание':'Мимо',`${String.fromCharCode(65+c)}${r+1}`)}catch(err){showError(err)}finally{busy=false}}

  function renderResult(stage){const won=room.result?.winner===identity.role,draw=!room.result?.winner;stage.innerHTML=`<div class="match-result"><span>${draw?'◇':won?'◆':'○'}</span><h2>${draw?'Ничья':won?'Победа':'Поражение'}</h2><p>${resultReason(room.result?.reason)}</p><button class="btn btn-primary" data-rematch>Предложить реванш</button><small>${room.rematch?.[other(identity.role)]?'Соперник уже ждёт реванш':'Для старта нужны оба игрока'}</small></div>`;stage.querySelector('[data-rematch]').onclick=()=>updateRoomAction(identity.code,identity,'rematch',{gameState:initialOnlineState(game)}).catch(showError)}
  function showDrawOffer(){if(document.querySelector('[data-draw-modal]'))return;modal({title:'Соперник предлагает ничью',text:'Завершить партию без победителя?',confirm:'Принять ничью',onConfirm:()=>updateRoomAction(identity.code,identity,'draw-accept').catch(showError),onCancel:()=>updateRoomAction(identity.code,identity,'draw-decline').catch(showError),extra:'<div data-draw-modal></div>'})}
  function confirmResign(){modal({title:'Сдаться?',text:'Соперник будет объявлен победителем.',danger:true,confirm:'Сдаться',onConfirm:()=>updateRoomAction(identity.code,identity,'resign').catch(showError)})}
  function confirmLeave(){modal({title:'Выйти из комнаты?',text:'Матч будет завершён, а соперник увидит ваш выход.',danger:true,confirm:'Выйти',onConfirm:async()=>{await leaveRoom(identity.code,identity).catch(()=>{});unsubscribe?.();identity=null;room=null;showLobby()}})}
  function watchPresence(){clearTimeout(disconnectTimer);if(room.status!=='playing')return;const missing=other(identity.role),player=room[missing];if(player&&!room.presence?.[player.id])disconnectTimer=setTimeout(()=>markDisconnected(identity.code,identity,missing).catch(()=>{}),6000)}
  function battleshipWarning(){return game==='battleship'?'<p class="privacy-note">Учебное ограничение: координаты флота скрыты интерфейсом, но доступны авторизованным участникам в данных комнаты. Для турнирной защиты нужен доверенный сервер проверки ходов.</p>':''}
  function showError(err){const raw=err?.message||'',permission=/permission.?denied/i.test(raw)||err?.code==='PERMISSION_DENIED'||err?.code==='permission-denied';toast('Не удалось выполнить действие',permission?'Firebase отклонил запрос. Опубликуйте актуальный firebase.rules.json во вкладке Rules.':raw||'Проверьте соединение и настройки Firebase.')}
  function setBusy(button,value,label){busy=value;button.disabled=value;button.textContent=label}
}

function chessInitial(){const b=Array.from({length:8},()=>Array(8).fill(null)),back=['r','n','b','q','k','b','n','r'];for(let c=0;c<8;c++){b[0][c]='b'+back[c];b[1][c]='bp';b[6][c]='wp';b[7][c]='w'+back[c]}return b}
function chessPseudo(b,r,c){const p=b[r]?.[c];if(!p)return[];const col=p[0],t=p[1],out=[],add=(rr,cc)=>{if(rr<0||cc<0||rr>7||cc>7)return false;if(!b[rr][cc]){out.push([rr,cc]);return true}if(b[rr][cc][0]!==col)out.push([rr,cc]);return false},ray=(dr,dc)=>{let rr=r+dr,cc=c+dc;while(add(rr,cc)){rr+=dr;cc+=dc}};if(t==='p'){const d=col==='w'?-1:1;if(!b[r+d]?.[c]){out.push([r+d,c]);const start=col==='w'?6:1;if(r===start&&!b[r+2*d][c])out.push([r+2*d,c])}for(const dc of[-1,1])if(b[r+d]?.[c+dc]&&b[r+d][c+dc][0]!==col)out.push([r+d,c+dc])}if(t==='n')for(const[d,e]of[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]])add(r+d,c+e);if('brq'.includes(t)){if(t!=='b'){ray(1,0);ray(-1,0);ray(0,1);ray(0,-1)}if(t!=='r'){ray(1,1);ray(1,-1);ray(-1,1);ray(-1,-1)}}if(t==='k')for(let d=-1;d<=1;d++)for(let e=-1;e<=1;e++)if(d||e)add(r+d,c+e);return out}
function chessLegal(b,r,c,rights={}){const p=b[r]?.[c];if(!p)return[];const moves=chessPseudo(b,r,c).filter(([rr,cc])=>{const copy=b.map(x=>[...x]);copy[rr][cc]=copy[r][c];copy[r][c]=null;return !isKingAttacked(copy,p[0])});if(p[1]==='k'&&c===4&&!isKingAttacked(b,p[0])){const row=p[0]==='w'?7:0;if(r===row&&rights[p[0]+'K']&&b[row][5]===null&&b[row][6]===null&&b[row][7]===p[0]+'r'&&kingPathSafe(b,p[0],row,[5,6]))moves.push([row,6]);if(r===row&&rights[p[0]+'Q']&&b[row][1]===null&&b[row][2]===null&&b[row][3]===null&&b[row][0]===p[0]+'r'&&kingPathSafe(b,p[0],row,[3,2]))moves.push([row,2])}return moves}
function isKingAttacked(b,color){let king=null;for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(b[r][c]===color+'k')king=[r,c];if(!king)return true;const enemy=color==='w'?'b':'w';for(let r=0;r<8;r++)for(let c=0;c<8;c++){const p=b[r][c];if(p?.[0]!==enemy)continue;if(p[1]==='p'){const d=enemy==='w'?-1:1;if((r+d===king[0])&&(c-1===king[1]||c+1===king[1]))return true}else if(chessPseudo(b,r,c).some(x=>x[0]===king[0]&&x[1]===king[1]))return true}return false}
function hasChessMove(b,color,rights){for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(b[r][c]?.[0]===color&&chessLegal(b,r,c,rights).length)return true;return false}
function kingPathSafe(b,color,row,cols){for(const col of cols){const copy=b.map(x=>[...x]);copy[row][col]=copy[row][4];copy[row][4]=null;if(isKingAttacked(copy,color))return false}return true}
function updateCastlingRights(rights,piece,from,captured,to){const color=piece[0];if(piece[1]==='k'){rights[color+'K']=false;rights[color+'Q']=false}if(piece[1]==='r'){if(from[1]===0)rights[color+'Q']=false;if(from[1]===7)rights[color+'K']=false}if(captured?.[1]==='r'){const enemy=captured[0];if(to[1]===0)rights[enemy+'Q']=false;if(to[1]===7)rights[enemy+'K']=false}}
function checkersInitial(){const b=Array.from({length:8},()=>Array(8).fill(null));for(let r=0;r<3;r++)for(let c=0;c<8;c++)if((r+c)%2)b[r][c]='c';for(let r=5;r<8;r++)for(let c=0;c<8;c++)if((r+c)%2)b[r][c]='r';return b}
function checkerCaptures(b,r,c,color){const p=b[r]?.[c],out=[];if(!p)return out;const dirs=p===p.toUpperCase()?[-1,1]:[color==='r'?-1:1];for(const dr of dirs)for(const dc of[-1,1]){const mid=b[r+dr]?.[c+dc],rr=r+2*dr,cc=c+2*dc;if(mid&&mid.toLowerCase()!==color&&rr>=0&&rr<8&&cc>=0&&cc<8&&!b[rr][cc])out.push([rr,cc])}return out}
function anyCapture(b,color){for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(b[r][c]?.toLowerCase()===color&&checkerCaptures(b,r,c,color).length)return true;return false}
function checkerMoves(b,r,c,color,forced){if(forced&&(forced[0]!==r||forced[1]!==c))return[];const caps=checkerCaptures(b,r,c,color);if(caps.length||anyCapture(b,color))return caps;const p=b[r]?.[c],out=[],dirs=p===p?.toUpperCase()?[-1,1]:[color==='r'?-1:1];for(const dr of dirs)for(const dc of[-1,1])if(b[r+dr]?.[c+dc]===null)out.push([r+dr,c+dc]);return out}
function hasCheckerMove(b,color){for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(b[r][c]?.toLowerCase()===color&&checkerMoves(b,r,c,color,null).length)return true;return false}
function seaFleet(){const cells=Array.from({length:10},()=>Array(10).fill(0)),fleet=[4,3,3,2,2,2,1,1,1,1];for(const len of fleet){let placed=false;while(!placed){const v=Math.random()<.5,r=Math.floor(Math.random()*(v?11-len:10)),c=Math.floor(Math.random()*(v?10:11-len));placed=true;for(let i=0;i<len;i++){const rr=r+(v?i:0),cc=c+(v?0:i);for(let y=rr-1;y<=rr+1;y++)for(let x=cc-1;x<=cc+1;x++)if(cells[y]?.[x]===1)placed=false}if(placed)for(let i=0;i<len;i++)cells[r+(v?i:0)][c+(v?0:i)]=1}}return cells}
function other(role){return role==='host'?'guest':'host'}
function sideName(game,role){return game==='chess'?(role==='host'?'белые':'чёрные'):game==='checkers'?(role==='host'?'красные':'светлые'):'флот'}
function statusText(room){if(room.status==='waiting')return'WAITING';if(room.status==='playing')return'LIVE';if(room.status==='abandoned')return'DISCONNECT';return'FINISHED'}
function formatMove(m){return m?`${String.fromCharCode(65+m.from[1])}${8-m.from[0]} → ${String.fromCharCode(65+m.to[1])}${8-m.to[0]}`:''}
function resultReason(reason){return({checkmate:'Мат. Королю некуда отступать.',stalemate:'Пат: допустимых ходов нет.',capture:'У соперника не осталось хода.',fleet:'Флот соперника уничтожен.',resign:'Соперник завершил партию.',draw:'Предложение ничьей принято.',disconnect:'Соперник покинул комнату.'})[reason]||'Матч завершён.'}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
